<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="acer-PC" name="com.tb.ThinkBridgeAssesment.TestScenarios" tests="4" failures="0" timestamp="2021-01-29T02:40:54 IST" time="0.016" errors="1">
  <testcase name="beforeTest" time="0.016" classname="com.tb.ThinkBridgeAssesment.TestScenarios">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElements(DefaultElementLocator.java:85)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementListHandler.invoke(LocatingElementListHandler.java:36)
at com.sun.proxy.$Proxy10.size(Unknown Source)
at com.tb.ThinkBridgeAssesment.ThinkBridgeBean.selectLanguage(ThinkBridgeBean.java:85)
at com.tb.ThinkBridgeAssesment.TestScenarios.beforeTest(TestScenarios.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeTest -->
  <system-out/>
  <testcase name="TC01_Title_Validation" time="0.000" classname="com.tb.ThinkBridgeAssesment.TestScenarios">
    <skipped/>
  </testcase> <!-- TC01_Title_Validation -->
  <system-out/>
  <testcase name="TC02_Valid_Credentials_Validation" time="0.000" classname="com.tb.ThinkBridgeAssesment.TestScenarios">
    <skipped/>
  </testcase> <!-- TC02_Valid_Credentials_Validation -->
  <system-out/>
  <testcase name="TC03_InValid_Credentials_Validation" time="0.000" classname="com.tb.ThinkBridgeAssesment.TestScenarios">
    <skipped/>
  </testcase> <!-- TC03_InValid_Credentials_Validation -->
  <system-out/>
</testsuite> <!-- com.tb.ThinkBridgeAssesment.TestScenarios -->
